spring:
  application:
    name: validacion-service


server:
  port: 8001


eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}


info:
  app:
    name: EurekaClient validacion-service

management:
  endpoints:
    web:
      exposure:
        include: health,beans,loggers,info
  info:
    env:
      enabled: true
  java:
    enabled: true