spring:
  application:
    name: registro-service

server:
  port: 8020

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.int}


management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    env:
      show-values: WHEN_AUTHORIZED
  info:
    env:
      enabled: true

info:
  app:
    name: EurekaClient registro-service
  java:
    version: ${java.version}